version: '3.8'

services:
  freshrss:
    image: bfren/freshrss:latest
    container_name: freshrss
    environment:
      - BF_FR_ENVIRONMENT=production
      - BF_FR_BASE_URL=${BF_FR_BASE_URL}
      - BF_FR_LANGUAGE=zh-cn
      - BF_FR_USER_NAME=${BF_FR_USER}
      - BF_FR_USER_PASS=${BF_FR_PASS}
      - BF_FR_DB_HOST=${BF_FR_DB_HOST}
      - BF_FR_DB_USER=${BF_FR_DB_USER}
      - BF_FR_DB_PASS=${BF_FR_DB_PASS}
      - BF_FR_DB_NAME=${BF_FR_DB_NAME}
      - BF_FR_DB_PREFIX=fr
    ports:
      - "10000:80"
